# Generated by Django 5.1.5 on 2025-01-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_HM', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('TN', 'Танки'), ('DD', 'ДД'), ('HL', 'Хиллеры'), ('ME', 'Торговцы'), ('GM', 'Гилдмастера'), ('QG', 'Квестгиверы'), ('BS', 'Кузнецы'), ('TS', 'Кожевники'), ('PM', 'Зельевары'), ('SM', 'Мастера заклинаний'), ('BU', 'Куплю'), ('SL', 'Продам')], default='TN', max_length=20),
        ),
    ]
