# Generated by Django 5.1.5 on 2025-01-24 04:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_HM', '0007_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='text_title_news',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
