# Generated by Django 5.1.5 on 2025-01-24 05:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_HM', '0008_delete_video_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_title_news',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
